import { db, settingsTable, icd10CodesTable } from "@workspace/db";
import { eq } from "drizzle-orm";

const ICD10_SEED: Array<{ code: string; title: string; description?: string; risks?: string; isFavorite?: boolean }> = [
  { code: "F00", title: "Démence dans la maladie d'Alzheimer", description: "Démence survenant dans la maladie d'Alzheimer.", risks: "Perte d'autonomie, errance, troubles du comportement.", isFavorite: true },
  { code: "F00.0", title: "Démence dans la maladie d'Alzheimer, à début précoce", description: "Début avant 65 ans, progression rapide avec troubles multiples des fonctions corticales supérieures." },
  { code: "F00.1", title: "Démence dans la maladie d'Alzheimer, à début tardif", description: "Début après 65 ans, évolution habituellement lente avec atteinte de la mémoire au premier plan." },
  { code: "F00.2", title: "Démence dans la maladie d'Alzheimer, forme atypique ou mixte" },
  { code: "F00.9", title: "Démence dans la maladie d'Alzheimer, sans précision" },
  { code: "F01", title: "Démence vasculaire", description: "Démence consécutive à des infarctus cérébraux multiples ou à des lésions vasculaires cérébrales." },
  { code: "F01.0", title: "Démence vasculaire à début aigu" },
  { code: "F01.1", title: "Démence par infarctus multiples" },
  { code: "F01.2", title: "Démence vasculaire sous-corticale" },
  { code: "F01.3", title: "Démence vasculaire mixte, corticale et sous-corticale" },
  { code: "F01.8", title: "Autres démences vasculaires" },
  { code: "F01.9", title: "Démence vasculaire, sans précision" },
  { code: "F02", title: "Démence au cours d'autres maladies classées ailleurs" },
  { code: "F02.0", title: "Démence de la maladie de Pick" },
  { code: "F02.1", title: "Démence de la maladie de Creutzfeldt-Jakob" },
  { code: "F02.2", title: "Démence de la maladie de Huntington" },
  { code: "F02.3", title: "Démence de la maladie de Parkinson" },
  { code: "F02.4", title: "Démence due à l'infection par le VIH" },
  { code: "F02.8", title: "Démence au cours d'autres maladies précisées" },
  { code: "F03", title: "Démence, sans précision" },
  { code: "F04", title: "Syndrome amnésique organique non lié à l'alcool ou à d'autres substances" },
  { code: "F05", title: "Delirium non lié à l'alcool ou à d'autres substances", risks: "Agitation, confusion, risque de chute ou de fuite." },
  { code: "F05.0", title: "Delirium non lié à une démence" },
  { code: "F05.1", title: "Delirium surajouté à une démence" },
  { code: "F05.8", title: "Autres delirium" },
  { code: "F05.9", title: "Delirium, sans précision" },
  { code: "F06", title: "Autres troubles mentaux dus à une lésion ou une maladie cérébrale ou à une affection somatique" },
  { code: "F06.0", title: "Hallucinose organique" },
  { code: "F06.1", title: "État catatonique organique" },
  { code: "F06.2", title: "Trouble délirant organique" },
  { code: "F06.3", title: "Troubles de l'humeur organiques" },
  { code: "F06.4", title: "Troubles anxieux organiques" },
  { code: "F06.5", title: "Trouble dissociatif organique" },
  { code: "F06.6", title: "Trouble émotionnellement labile (asthénique) organique" },
  { code: "F06.7", title: "Trouble cognitif léger" },
  { code: "F06.8", title: "Autres troubles mentaux précisés dus à une lésion cérébrale" },
  { code: "F06.9", title: "Trouble mental non précisé dû à une lésion cérébrale" },
  { code: "F07", title: "Troubles de la personnalité et du comportement dus à une affection cérébrale" },
  { code: "F07.0", title: "Trouble de la personnalité organique" },
  { code: "F07.1", title: "Syndrome post-encéphalitique" },
  { code: "F07.2", title: "Syndrome post-commotionnel" },
  { code: "F07.8", title: "Autres troubles organiques de la personnalité et du comportement" },
  { code: "F07.9", title: "Trouble organique de la personnalité et du comportement, sans précision" },
  { code: "F09", title: "Trouble mental organique ou symptomatique, sans précision" },

  { code: "F10", title: "Troubles mentaux et du comportement liés à l'utilisation d'alcool", description: "Intoxication aiguë, usage nocif, syndrome de dépendance, état de sevrage.", risks: "Rechute, complications somatiques, isolement social, violence.", isFavorite: true },
  { code: "F10.0", title: "Intoxication aiguë à l'alcool" },
  { code: "F10.1", title: "Utilisation nocive d'alcool pour la santé" },
  { code: "F10.2", title: "Syndrome de dépendance à l'alcool", risks: "Sevrage sévère, delirium tremens, complications hépatiques." },
  { code: "F10.3", title: "Syndrome de sevrage alcoolique" },
  { code: "F10.4", title: "Syndrome de sevrage alcoolique avec delirium (delirium tremens)" },
  { code: "F10.5", title: "Trouble psychotique lié à l'alcool" },
  { code: "F10.6", title: "Syndrome amnésique lié à l'alcool (syndrome de Korsakoff)" },
  { code: "F10.7", title: "Trouble psychotique résiduel lié à l'alcool" },
  { code: "F10.8", title: "Autres troubles mentaux et du comportement liés à l'alcool" },
  { code: "F10.9", title: "Trouble mental lié à l'alcool, sans précision" },
  { code: "F11", title: "Troubles mentaux et du comportement liés à l'utilisation d'opioïdes", risks: "Surdosage fatal, infections, criminalité." },
  { code: "F11.0", title: "Intoxication aiguë aux opioïdes" },
  { code: "F11.1", title: "Utilisation nocive d'opioïdes" },
  { code: "F11.2", title: "Syndrome de dépendance aux opioïdes" },
  { code: "F11.3", title: "Syndrome de sevrage aux opioïdes" },
  { code: "F12", title: "Troubles mentaux et du comportement liés à l'utilisation de cannabinoïdes" },
  { code: "F12.0", title: "Intoxication aiguë aux cannabinoïdes" },
  { code: "F12.1", title: "Utilisation nocive de cannabinoïdes" },
  { code: "F12.2", title: "Syndrome de dépendance aux cannabinoïdes" },
  { code: "F13", title: "Troubles mentaux et du comportement liés à l'utilisation de sédatifs ou d'hypnotiques" },
  { code: "F13.0", title: "Intoxication aiguë aux sédatifs/hypnotiques" },
  { code: "F13.1", title: "Utilisation nocive de sédatifs/hypnotiques" },
  { code: "F13.2", title: "Syndrome de dépendance aux sédatifs/hypnotiques" },
  { code: "F13.3", title: "Syndrome de sevrage aux sédatifs/hypnotiques" },
  { code: "F14", title: "Troubles mentaux et du comportement liés à l'utilisation de cocaïne" },
  { code: "F14.0", title: "Intoxication aiguë à la cocaïne" },
  { code: "F14.1", title: "Utilisation nocive de cocaïne" },
  { code: "F14.2", title: "Syndrome de dépendance à la cocaïne" },
  { code: "F15", title: "Troubles mentaux et du comportement liés à l'utilisation de stimulants" },
  { code: "F15.0", title: "Intoxication aiguë aux stimulants (amphétamines, etc.)" },
  { code: "F15.1", title: "Utilisation nocive de stimulants" },
  { code: "F15.2", title: "Syndrome de dépendance aux stimulants" },
  { code: "F16", title: "Troubles mentaux et du comportement liés à l'utilisation d'hallucinogènes" },
  { code: "F17", title: "Troubles mentaux et du comportement liés à l'utilisation de tabac" },
  { code: "F17.1", title: "Utilisation nocive du tabac" },
  { code: "F17.2", title: "Syndrome de dépendance au tabac" },
  { code: "F18", title: "Troubles mentaux et du comportement liés à l'utilisation de solvants volatils" },
  { code: "F19", title: "Troubles mentaux et du comportement liés à l'utilisation de plusieurs drogues ou d'autres substances psychoactives" },
  { code: "F19.0", title: "Intoxication aiguë à plusieurs substances" },
  { code: "F19.1", title: "Utilisation nocive de plusieurs substances" },
  { code: "F19.2", title: "Syndrome de dépendance à plusieurs substances" },

  { code: "F20", title: "Schizophrénie", description: "Distorsions fondamentales de la pensée et de la perception, affects inappropriés ou émoussés.", risks: "Passage à l'acte hétéro/auto-agressif, désinsertion sociale, rechute sans traitement.", isFavorite: true },
  { code: "F20.0", title: "Schizophrénie paranoïde", description: "Idées délirantes persistantes et hallucinations auditives au premier plan." },
  { code: "F20.1", title: "Schizophrénie hébéphrénique", description: "Trouble affectif et du comportement prédominant, idées délirantes fragmentées." },
  { code: "F20.2", title: "Schizophrénie catatonique", description: "Troubles psychomoteurs prédominants : stupeur, agitation, catalepsie." },
  { code: "F20.3", title: "Schizophrénie indifférenciée" },
  { code: "F20.4", title: "Dépression post-schizophrénique" },
  { code: "F20.5", title: "Schizophrénie résiduelle", description: "Phase chronique avec symptômes négatifs prédominants." },
  { code: "F20.6", title: "Schizophrénie simple" },
  { code: "F20.8", title: "Autres formes de schizophrénie" },
  { code: "F20.9", title: "Schizophrénie, sans précision" },
  { code: "F21", title: "Trouble schizotypique", description: "Comportement excentrique, anomalies de la pensée et des émotions ressemblant à la schizophrénie." },
  { code: "F22", title: "Troubles délirants persistants", description: "Idée ou système délirant isolé, durable, sans hallucinations importantes." },
  { code: "F22.0", title: "Trouble délirant", risks: "Comportements médico-légaux, isolement." },
  { code: "F22.8", title: "Autres troubles délirants persistants" },
  { code: "F22.9", title: "Trouble délirant persistant, sans précision" },
  { code: "F23", title: "Troubles psychotiques aigus et transitoires" },
  { code: "F23.0", title: "Trouble psychotique aigu polymorphe sans symptômes schizophréniques" },
  { code: "F23.1", title: "Trouble psychotique aigu polymorphe avec symptômes schizophréniques" },
  { code: "F23.2", title: "Trouble psychotique aigu de type schizophrénique" },
  { code: "F23.3", title: "Autre trouble psychotique aigu à prédominance d'idées délirantes" },
  { code: "F23.8", title: "Autres troubles psychotiques aigus et transitoires" },
  { code: "F23.9", title: "Trouble psychotique aigu et transitoire, sans précision" },
  { code: "F24", title: "Trouble délirant induit" },
  { code: "F25", title: "Troubles schizo-affectifs", description: "Épisodes où des symptômes schizophréniques et affectifs sont tous deux au premier plan." },
  { code: "F25.0", title: "Trouble schizo-affectif, type maniaque" },
  { code: "F25.1", title: "Trouble schizo-affectif, type dépressif", risks: "Risque suicidaire élevé." },
  { code: "F25.2", title: "Trouble schizo-affectif, type mixte" },
  { code: "F25.8", title: "Autres troubles schizo-affectifs" },
  { code: "F25.9", title: "Trouble schizo-affectif, sans précision" },
  { code: "F28", title: "Autres troubles psychotiques non organiques" },
  { code: "F29", title: "Psychose non organique, sans précision" },

  { code: "F30", title: "Épisode maniaque", description: "Élévation de l'humeur, augmentation de l'énergie et de l'activité, réduction du besoin de sommeil.", risks: "Conduites à risque (finances, sexualité), hétéro-agressivité, désinhibition." },
  { code: "F30.0", title: "Hypomanie", description: "Forme atténuée de manie, humeur légèrement élevée, énergie accrue, productivité augmentée sans rupture franche avec la réalité." },
  { code: "F30.1", title: "Manie sans symptômes psychotiques", description: "Humeur exaltée ou irritable, hyperactivité, logorrhée, réduction du besoin de sommeil, grandiosité.", risks: "Conduites à risque graves, dépenses excessives, comportement sexuel désinhibé." },
  { code: "F30.2", title: "Manie avec symptômes psychotiques", description: "Manie sévère associée à des idées délirantes de grandeur ou à des hallucinations.", risks: "Dangerosité élevée, nécessite souvent une hospitalisation." },
  { code: "F30.8", title: "Autres épisodes maniaques" },
  { code: "F30.9", title: "Épisode maniaque, sans précision" },
  { code: "F31", title: "Trouble affectif bipolaire", description: "Alternance d'épisodes maniaques/hypomaniaques et dépressifs.", risks: "Risque suicidaire élevé (en phase dépressive), conduites à risque (en phase maniaque).", isFavorite: true },
  { code: "F31.0", title: "Trouble bipolaire, épisode actuel hypomaniaque" },
  { code: "F31.1", title: "Trouble bipolaire, épisode actuel maniaque sans symptômes psychotiques" },
  { code: "F31.2", title: "Trouble bipolaire, épisode actuel maniaque avec symptômes psychotiques" },
  { code: "F31.3", title: "Trouble bipolaire, épisode actuel dépressif léger ou moyen" },
  { code: "F31.4", title: "Trouble bipolaire, épisode actuel dépressif sévère sans symptômes psychotiques" },
  { code: "F31.5", title: "Trouble bipolaire, épisode actuel dépressif sévère avec symptômes psychotiques", risks: "Risque suicidaire très élevé." },
  { code: "F31.6", title: "Trouble bipolaire, épisode actuel mixte" },
  { code: "F31.7", title: "Trouble bipolaire, rémission actuelle" },
  { code: "F31.8", title: "Autre trouble bipolaire" },
  { code: "F31.9", title: "Trouble bipolaire, sans précision" },
  { code: "F32", title: "Épisode dépressif", description: "Abaissement de l'humeur, réduction de l'énergie et de l'activité, anhédonie.", risks: "Risque suicidaire, isolement, dénutrition.", isFavorite: true },
  { code: "F32.0", title: "Épisode dépressif léger" },
  { code: "F32.1", title: "Épisode dépressif moyen" },
  { code: "F32.2", title: "Épisode dépressif sévère sans symptômes psychotiques", risks: "Risque suicidaire élevé, nécessite souvent une hospitalisation." },
  { code: "F32.3", title: "Épisode dépressif sévère avec symptômes psychotiques", risks: "Risque suicidaire très élevé, urgence psychiatrique." },
  { code: "F32.8", title: "Autres épisodes dépressifs" },
  { code: "F32.9", title: "Épisode dépressif, sans précision" },
  { code: "F33", title: "Trouble dépressif récurrent", description: "Répétition d'épisodes dépressifs sans antécédent d'hypomanie ou de manie." },
  { code: "F33.0", title: "Trouble dépressif récurrent, épisode actuel léger" },
  { code: "F33.1", title: "Trouble dépressif récurrent, épisode actuel moyen" },
  { code: "F33.2", title: "Trouble dépressif récurrent, épisode actuel sévère sans symptômes psychotiques" },
  { code: "F33.3", title: "Trouble dépressif récurrent, épisode actuel sévère avec symptômes psychotiques" },
  { code: "F33.4", title: "Trouble dépressif récurrent, actuellement en rémission" },
  { code: "F33.8", title: "Autres troubles dépressifs récurrents" },
  { code: "F33.9", title: "Trouble dépressif récurrent, sans précision" },
  { code: "F34", title: "Troubles de l'humeur persistants" },
  { code: "F34.0", title: "Cyclothymie", description: "Instabilité persistante de l'humeur avec alternance de périodes légèrement dépressives et légèrement élevées." },
  { code: "F34.1", title: "Dysthymie", description: "Dépression chronique d'intensité légère, présente la plupart du temps depuis au moins 2 ans." },
  { code: "F34.8", title: "Autres troubles de l'humeur persistants" },
  { code: "F34.9", title: "Trouble de l'humeur persistant, sans précision" },
  { code: "F38", title: "Autres troubles de l'humeur" },
  { code: "F38.0", title: "Autres troubles de l'humeur isolés" },
  { code: "F38.1", title: "Autres troubles de l'humeur récurrents" },
  { code: "F38.8", title: "Autres troubles de l'humeur précisés" },
  { code: "F39", title: "Trouble de l'humeur, sans précision" },

  { code: "F40", title: "Troubles anxieux phobiques", description: "Anxiété provoquée exclusivement ou essentiellement par des situations déterminées." },
  { code: "F40.0", title: "Agoraphobie", description: "Anxiété dans les endroits publics, les transports, les foules." },
  { code: "F40.00", title: "Agoraphobie sans trouble panique" },
  { code: "F40.01", title: "Agoraphobie avec trouble panique" },
  { code: "F40.1", title: "Phobies sociales", description: "Crainte d'être observé ou jugé négativement par autrui." },
  { code: "F40.2", title: "Phobies spécifiques (isolées)", description: "Peur excessive d'un objet ou d'une situation spécifique (animaux, hauteur, sang...)." },
  { code: "F40.8", title: "Autres troubles anxieux phobiques" },
  { code: "F40.9", title: "Trouble anxieux phobique, sans précision" },
  { code: "F41", title: "Autres troubles anxieux", description: "L'anxiété est le symptôme principal et n'est pas limitée à une situation particulière.", risks: "Attaques de panique, évitement social, dépendance aux anxiolytiques.", isFavorite: true },
  { code: "F41.0", title: "Trouble panique (anxiété épisodique paroxystique)", description: "Attaques récurrentes de panique avec crainte d'une nouvelle attaque." },
  { code: "F41.1", title: "Trouble anxieux généralisé", description: "Anxiété généralisée et persistante, non limitée à des situations particulières." },
  { code: "F41.2", title: "Trouble anxieux et dépressif mixte" },
  { code: "F41.3", title: "Autre trouble anxieux mixte" },
  { code: "F41.8", title: "Autres troubles anxieux précisés" },
  { code: "F41.9", title: "Trouble anxieux, sans précision" },
  { code: "F42", title: "Trouble obsessionnel-compulsif", description: "Pensées obsédantes récurrentes et comportements compulsifs répétitifs." },
  { code: "F42.0", title: "Trouble obsessionnel-compulsif à prédominance de pensées ou de ruminations" },
  { code: "F42.1", title: "Trouble obsessionnel-compulsif à prédominance de comportements compulsifs (rituels obsessionnels)" },
  { code: "F42.2", title: "Trouble obsessionnel-compulsif mixte" },
  { code: "F42.8", title: "Autres troubles obsessionnels-compulsifs" },
  { code: "F42.9", title: "Trouble obsessionnel-compulsif, sans précision" },
  { code: "F43", title: "Réactions à un facteur de stress sévère et troubles de l'adaptation" },
  { code: "F43.0", title: "Réaction aiguë à un facteur de stress", description: "Réaction transitoire à un facteur de stress exceptionnel." },
  { code: "F43.1", title: "État de stress post-traumatique (ESPT)", description: "Réponse différée à un événement traumatique, avec reviviscences, évitement et hypervigilance.", risks: "Risque suicidaire, addictions, chronicisation." },
  { code: "F43.2", title: "Troubles de l'adaptation", description: "États de détresse subjective et de perturbation émotionnelle en réponse à un facteur de stress identifiable." },
  { code: "F43.20", title: "Réaction dépressive brève" },
  { code: "F43.21", title: "Réaction dépressive prolongée" },
  { code: "F43.22", title: "Réaction mixte anxieuse et dépressive" },
  { code: "F43.23", title: "Trouble de l'adaptation avec perturbation prédominante d'autres émotions" },
  { code: "F43.24", title: "Trouble de l'adaptation avec perturbation prédominante des conduites" },
  { code: "F43.25", title: "Trouble de l'adaptation avec perturbation mixte des émotions et des conduites" },
  { code: "F43.28", title: "Troubles de l'adaptation avec d'autres symptômes prédominants précisés" },
  { code: "F43.8", title: "Autres réactions à un facteur de stress sévère" },
  { code: "F43.9", title: "Réaction à un facteur de stress sévère, sans précision" },
  { code: "F44", title: "Troubles dissociatifs (de conversion)", description: "Perte partielle ou totale des fonctions normales (mémoire, identité, mouvements) sans cause organique." },
  { code: "F44.0", title: "Amnésie dissociative" },
  { code: "F44.1", title: "Fugue dissociative" },
  { code: "F44.2", title: "Stupeur dissociative" },
  { code: "F44.3", title: "États de transe et de possession" },
  { code: "F44.4", title: "Troubles moteurs dissociatifs" },
  { code: "F44.5", title: "Convulsions dissociatives" },
  { code: "F44.6", title: "Anesthésies et pertes sensorielles dissociatives" },
  { code: "F44.7", title: "Troubles dissociatifs (de conversion) mixtes" },
  { code: "F44.8", title: "Autres troubles dissociatifs" },
  { code: "F44.80", title: "Syndrome de Ganser" },
  { code: "F44.81", title: "Trouble de la personnalité multiple" },
  { code: "F44.9", title: "Trouble dissociatif, sans précision" },
  { code: "F45", title: "Troubles somatoformes", description: "Symptômes physiques répétés sans explication organique, demande de soins médicaux persistante." },
  { code: "F45.0", title: "Trouble somatisation" },
  { code: "F45.1", title: "Trouble somatoforme indifférencié" },
  { code: "F45.2", title: "Trouble hypocondriaque" },
  { code: "F45.3", title: "Dysfonctionnement neurovégétatif somatoforme" },
  { code: "F45.4", title: "Trouble douloureux somatoforme persistant" },
  { code: "F45.8", title: "Autres troubles somatoformes" },
  { code: "F45.9", title: "Trouble somatoforme, sans précision" },
  { code: "F48", title: "Autres troubles névrotiques" },
  { code: "F48.0", title: "Neurasthénie" },
  { code: "F48.1", title: "Syndrome de dépersonnalisation-déréalisation" },
  { code: "F48.8", title: "Autres troubles névrotiques précisés" },
  { code: "F48.9", title: "Trouble névrotique, sans précision" },

  { code: "F50", title: "Troubles des conduites alimentaires" },
  { code: "F50.0", title: "Anorexie mentale", description: "Refus de maintenir un poids corporel normal, peur intense de prendre du poids.", risks: "Complications somatiques sévères, risque vital, risque suicidaire." },
  { code: "F50.1", title: "Anorexie mentale atypique" },
  { code: "F50.2", title: "Boulimie", description: "Épisodes récurrents d'hyperphagie avec comportements compensatoires.", risks: "Complications somatiques (électrolytes), risque suicidaire." },
  { code: "F50.3", title: "Boulimie atypique" },
  { code: "F50.4", title: "Hyperphagie associée à d'autres perturbations psychologiques" },
  { code: "F50.5", title: "Vomissements associés à d'autres perturbations psychologiques" },
  { code: "F50.8", title: "Autres troubles des conduites alimentaires" },
  { code: "F50.9", title: "Trouble des conduites alimentaires, sans précision" },
  { code: "F51", title: "Troubles du sommeil non organiques" },
  { code: "F51.0", title: "Insomnie non organique" },
  { code: "F51.1", title: "Hypersomnie non organique" },
  { code: "F51.2", title: "Trouble du rythme veille-sommeil non organique" },
  { code: "F51.3", title: "Somnambulisme" },
  { code: "F51.4", title: "Terreurs nocturnes" },
  { code: "F51.5", title: "Cauchemars" },
  { code: "F51.8", title: "Autres troubles du sommeil non organiques" },
  { code: "F51.9", title: "Trouble du sommeil non organique, sans précision" },
  { code: "F52", title: "Dysfonction sexuelle non due à un trouble organique ni à une maladie" },
  { code: "F52.0", title: "Manque ou perte du désir sexuel" },
  { code: "F52.1", title: "Aversion sexuelle et manque de plaisir sexuel" },
  { code: "F52.2", title: "Échec de la réponse génitale" },
  { code: "F52.3", title: "Dysfonction orgasmique" },
  { code: "F52.4", title: "Éjaculation précoce" },
  { code: "F52.5", title: "Vaginisme non organique" },
  { code: "F52.6", title: "Dyspareunie non organique" },
  { code: "F52.7", title: "Hypersexualité" },
  { code: "F52.8", title: "Autres dysfonctions sexuelles" },
  { code: "F52.9", title: "Dysfonction sexuelle, sans précision" },
  { code: "F53", title: "Troubles mentaux et troubles du comportement associés à la puerpéralité" },
  { code: "F53.0", title: "Troubles mentaux légers associés à la puerpéralité (dépression du post-partum)" },
  { code: "F53.1", title: "Troubles mentaux sévères associés à la puerpéralité (psychose puerpérale)", risks: "Risque pour la mère et l'enfant, urgence psychiatrique." },
  { code: "F54", title: "Facteurs psychologiques et comportementaux associés à des maladies classées ailleurs" },
  { code: "F55", title: "Utilisation abusive de substances n'entraînant pas de dépendance" },
  { code: "F59", title: "Syndromes comportementaux associés à des perturbations physiologiques, sans précision" },

  { code: "F60", title: "Troubles spécifiques de la personnalité", description: "Modes de comportement durable, envahissant et inadapté, déviant nettement des normes culturelles.", risks: "Instabilité relationnelle, auto-mutilation, passages à l'acte.", isFavorite: true },
  { code: "F60.0", title: "Personnalité paranoïaque", description: "Méfiance et suspicion persistantes, tendance à interpréter les intentions d'autrui comme malveillantes." },
  { code: "F60.1", title: "Personnalité schizoïde", description: "Détachement des relations sociales, restriction des émotions." },
  { code: "F60.2", title: "Personnalité dyssociale (antisociale)", description: "Mépris des droits d'autrui, impulsivité, incapacité à maintenir des relations durables.", risks: "Comportements antisociaux, agressivité, criminalité." },
  { code: "F60.3", title: "Personnalité émotionnellement labile", description: "Impulsivité marquée avec instabilité émotionnelle. Inclut le trouble borderline." },
  { code: "F60.30", title: "Personnalité émotionnellement labile, type impulsif" },
  { code: "F60.31", title: "Personnalité émotionnellement labile, type borderline", risks: "Auto-mutilation, tentatives de suicide, instabilité relationnelle intense." },
  { code: "F60.4", title: "Personnalité histrionique", description: "Émotivité excessive, comportement de séduction, suggestibilité." },
  { code: "F60.5", title: "Personnalité anankastique (obsessionnelle-compulsive)", description: "Perfectionnisme, rigidité, indécision, préoccupation pour les détails." },
  { code: "F60.6", title: "Personnalité anxieuse (évitante)", description: "Inhibition sociale, sentiment d'inadéquation, hypersensibilité au jugement négatif." },
  { code: "F60.7", title: "Personnalité dépendante", description: "Besoin excessif d'être pris en charge, comportements soumis et adhésifs." },
  { code: "F60.8", title: "Autres troubles spécifiques de la personnalité" },
  { code: "F60.9", title: "Trouble de la personnalité, sans précision" },
  { code: "F61", title: "Troubles mixtes et autres troubles de la personnalité" },
  { code: "F62", title: "Modifications durables de la personnalité non attribuables à une lésion cérébrale" },
  { code: "F62.0", title: "Modification durable de la personnalité après une expérience de catastrophe" },
  { code: "F62.1", title: "Modification durable de la personnalité après une maladie psychiatrique" },
  { code: "F62.8", title: "Autres modifications durables de la personnalité" },
  { code: "F62.9", title: "Modification durable de la personnalité, sans précision" },
  { code: "F63", title: "Troubles des habitudes et des impulsions" },
  { code: "F63.0", title: "Jeu pathologique (ludomanie)" },
  { code: "F63.1", title: "Pyromanie" },
  { code: "F63.2", title: "Kleptomanie" },
  { code: "F63.3", title: "Trichotillomanie" },
  { code: "F63.8", title: "Autres troubles des habitudes et des impulsions" },
  { code: "F63.9", title: "Trouble des habitudes et des impulsions, sans précision" },
  { code: "F64", title: "Troubles de l'identité de genre" },
  { code: "F64.0", title: "Transsexualisme" },
  { code: "F64.1", title: "Travestisme bivalent" },
  { code: "F64.2", title: "Trouble de l'identité sexuelle dans l'enfance" },
  { code: "F64.8", title: "Autres troubles de l'identité de genre" },
  { code: "F64.9", title: "Trouble de l'identité de genre, sans précision" },
  { code: "F65", title: "Troubles de la préférence sexuelle" },
  { code: "F65.0", title: "Fétichisme" },
  { code: "F65.1", title: "Travestisme fétichiste" },
  { code: "F65.2", title: "Exhibitionnisme" },
  { code: "F65.3", title: "Voyeurisme" },
  { code: "F65.4", title: "Pédophilie" },
  { code: "F65.5", title: "Sadomasochisme" },
  { code: "F65.6", title: "Troubles multiples de la préférence sexuelle" },
  { code: "F65.8", title: "Autres troubles de la préférence sexuelle" },
  { code: "F65.9", title: "Trouble de la préférence sexuelle, sans précision" },
  { code: "F66", title: "Troubles psychologiques et comportementaux associés au développement sexuel" },
  { code: "F68", title: "Autres troubles de la personnalité et du comportement chez l'adulte" },
  { code: "F68.0", title: "Élaboration de symptômes physiques pour des raisons psychologiques" },
  { code: "F68.1", title: "Production intentionnelle de symptômes ou d'incapacités physiques ou psychologiques (syndrome de Münchhausen)" },
  { code: "F68.8", title: "Autres troubles précisés de la personnalité et du comportement" },
  { code: "F69", title: "Trouble de la personnalité et du comportement, sans précision" },

  { code: "F70", title: "Déficience intellectuelle légère", description: "QI 50–69 ; développement lent mais capacité d'autonomie sociale." },
  { code: "F71", title: "Déficience intellectuelle moyenne", description: "QI 35–49 ; autonomie partielle, nécessite un soutien." },
  { code: "F72", title: "Déficience intellectuelle grave", description: "QI 20–34 ; dépendance importante." },
  { code: "F73", title: "Déficience intellectuelle profonde", description: "QI inférieur à 20 ; dépendance totale." },
  { code: "F78", title: "Autre déficience intellectuelle" },
  { code: "F79", title: "Déficience intellectuelle, sans précision" },

  { code: "F80", title: "Troubles spécifiques du développement de la parole et du langage" },
  { code: "F80.0", title: "Troubles spécifiques de l'articulation" },
  { code: "F80.1", title: "Trouble du langage expressif" },
  { code: "F80.2", title: "Trouble de la réception du langage" },
  { code: "F80.3", title: "Aphasie acquise avec épilepsie (syndrome de Landau-Kleffner)" },
  { code: "F80.8", title: "Autres troubles du développement de la parole et du langage" },
  { code: "F80.9", title: "Trouble du développement de la parole et du langage, sans précision" },
  { code: "F81", title: "Troubles spécifiques des acquisitions scolaires" },
  { code: "F81.0", title: "Trouble spécifique de la lecture (dyslexie)" },
  { code: "F81.1", title: "Trouble spécifique de l'orthographe" },
  { code: "F81.2", title: "Trouble spécifique des aptitudes arithmétiques (dyscalculie)" },
  { code: "F81.3", title: "Trouble mixte des acquisitions scolaires" },
  { code: "F81.8", title: "Autres troubles des acquisitions scolaires" },
  { code: "F81.9", title: "Trouble des acquisitions scolaires, sans précision" },
  { code: "F82", title: "Trouble spécifique du développement moteur (dyspraxie)" },
  { code: "F83", title: "Troubles spécifiques mixtes du développement" },
  { code: "F84", title: "Troubles envahissants du développement" },
  { code: "F84.0", title: "Autisme infantile", description: "Développement altéré avant 3 ans : communication, interactions sociales, comportements répétitifs." },
  { code: "F84.1", title: "Autisme atypique" },
  { code: "F84.2", title: "Syndrome de Rett" },
  { code: "F84.3", title: "Autre trouble désintégratif de l'enfance" },
  { code: "F84.4", title: "Hyperactivité associée à un retard mental et à des mouvements stéréotypés" },
  { code: "F84.5", title: "Syndrome d'Asperger", description: "Altération des interactions sociales avec intérêts restreints, sans retard du langage." },
  { code: "F84.8", title: "Autres troubles envahissants du développement" },
  { code: "F84.9", title: "Trouble envahissant du développement, sans précision" },
  { code: "F88", title: "Autres troubles du développement psychologique" },
  { code: "F89", title: "Trouble du développement psychologique, sans précision" },

  { code: "F90", title: "Troubles hyperkinétiques" },
  { code: "F90.0", title: "Perturbation de l'activité et de l'attention (TDAH)", description: "Inattention, hyperactivité et impulsivité inadaptées à l'âge de développement." },
  { code: "F90.1", title: "Trouble hyperkinétique des conduites" },
  { code: "F90.8", title: "Autres troubles hyperkinétiques" },
  { code: "F90.9", title: "Trouble hyperkinétique, sans précision" },
  { code: "F91", title: "Troubles des conduites", description: "Comportement répétitif et persistant violant les droits d'autrui ou les normes sociales." },
  { code: "F91.0", title: "Trouble des conduites limité au milieu familial" },
  { code: "F91.1", title: "Trouble des conduites avec déficit de socialisation" },
  { code: "F91.2", title: "Trouble des conduites avec socialisation adéquate" },
  { code: "F91.3", title: "Trouble oppositionnel avec provocation" },
  { code: "F91.8", title: "Autres troubles des conduites" },
  { code: "F91.9", title: "Trouble des conduites, sans précision" },
  { code: "F92", title: "Troubles mixtes des conduites et troubles émotionnels" },
  { code: "F92.0", title: "Trouble des conduites dépressif" },
  { code: "F92.8", title: "Autres troubles mixtes des conduites et troubles émotionnels" },
  { code: "F92.9", title: "Trouble mixte des conduites et troubles émotionnels, sans précision" },
  { code: "F93", title: "Troubles émotionnels avec début spécifique à l'enfance" },
  { code: "F93.0", title: "Trouble anxieux de séparation de l'enfance" },
  { code: "F93.1", title: "Trouble anxieux phobique de l'enfance" },
  { code: "F93.2", title: "Trouble anxieux social de l'enfance" },
  { code: "F93.3", title: "Trouble de rivalité dans la fratrie" },
  { code: "F93.8", title: "Autres troubles émotionnels de l'enfance" },
  { code: "F93.9", title: "Trouble émotionnel de l'enfance, sans précision" },
  { code: "F94", title: "Troubles du fonctionnement social avec début spécifique à l'enfance et à l'adolescence" },
  { code: "F94.0", title: "Mutisme électif (sélectif)" },
  { code: "F94.1", title: "Trouble réactionnel de l'attachement de l'enfance" },
  { code: "F94.2", title: "Trouble de l'attachement de l'enfance avec désinhibition" },
  { code: "F94.8", title: "Autres troubles du fonctionnement social de l'enfance" },
  { code: "F94.9", title: "Trouble du fonctionnement social de l'enfance, sans précision" },
  { code: "F95", title: "Tics" },
  { code: "F95.0", title: "Tic transitoire" },
  { code: "F95.1", title: "Tic moteur ou vocal chronique" },
  { code: "F95.2", title: "Syndrome de Gilles de la Tourette" },
  { code: "F95.8", title: "Autres tics" },
  { code: "F95.9", title: "Tic, sans précision" },
  { code: "F98", title: "Autres troubles du comportement et troubles émotionnels de l'enfance et de l'adolescence" },
  { code: "F98.0", title: "Énurésie non organique" },
  { code: "F98.1", title: "Encoprésie non organique" },
  { code: "F98.2", title: "Trouble de l'alimentation du nourrisson et de l'enfant" },
  { code: "F98.3", title: "Pica du nourrisson et de l'enfant" },
  { code: "F98.4", title: "Mouvements stéréotypés" },
  { code: "F98.5", title: "Bégaiement" },
  { code: "F98.6", title: "Bredouillage" },
  { code: "F98.8", title: "Autres troubles du comportement et troubles émotionnels précisés de l'enfance" },
  { code: "F98.9", title: "Trouble du comportement et trouble émotionnel de l'enfance, sans précision" },
  { code: "F99", title: "Trouble mental, sans précision" },
];

async function seedIcd10Codes() {
  for (const entry of ICD10_SEED) {
    await db.insert(icd10CodesTable).values({
      code: entry.code,
      title: entry.title,
      description: entry.description ?? null,
      risks: entry.risks ?? null,
      isFavorite: entry.isFavorite ?? false,
    }).onConflictDoNothing();
  }
}

export async function seedDatabase() {
  await seedIcd10Codes();

  const defaults: Record<string, string[]> = {
    casemanagers: [],
    psychiatrists: [],
    medecinsfamille: [],
    articles: ["Article 71", "Article 72", "Article 73", "CAPL"],
    curatelles: ["Curatelle totale", "Curatelle partielle", "Tutelle", "Sauvegarde de justice"],
  };

  for (const [key, value] of Object.entries(defaults)) {
    const existing = await db.select().from(settingsTable)
      .where(eq(settingsTable.key, key))
      .limit(1);

    if (!existing[0]) {
      await db.insert(settingsTable).values({ key, value: JSON.stringify(value) });
    }
  }
}
